# Generated by Django 3.2.6 on 2021-08-05 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientes',
            name='observacoes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='cidade',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
